### ISSUE TITLE
Missing follow-utils

### ISSUE THREAD

**Issue by ajturner** [esridc/hub-components#19]
@jgravois I think there may be a missing file from your last check-in `utils/follow-utils`. 

I was upgrading the package versions and ran into this missing file and some other issues.

**Comment by jgravois** [comment]
greetings! 👋 

where do you see a reference to `utils/follow-utils`?

I just cloned the repo and ran:
```bash
npm install && npm start
```
and the local app worked just like the [live demo](https://esridc.github.io/hub-components/) (after a hard refresh anyway).

![Screen Shot 2020-02-18 at 9 44 18 PM](https://user-images.githubusercontent.com/3011734/74805402-d678c600-5297-11ea-9827-31f2d7c341d6.png)

**Comment by ajturner** [comment]
My fault. This was a component I was in the middle of refactoring. Specifically, I was moving the auth out of the Event details into a re-usable, lower-level `hub-button-auth`. Though now that I think about it, it probably can be a Prop on the `hub-button` if auth is expected.
